# Generated by Django 2.2.7 on 2020-01-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicData',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('pb_name', models.TextField(blank=True)),
                ('pb_goal', models.TextField(blank=True)),
                ('pb_target', models.TextField(blank=True)),
                ('pb_criteria', models.TextField(blank=True)),
                ('pb_support_desc', models.TextField(blank=True)),
                ('pb_online_url', models.TextField(blank=True)),
                ('pb_submit_step', models.TextField(blank=True)),
                ('pb_submit_date', models.TextField(blank=True)),
                ('pb_need_paper', models.TextField(blank=True)),
                ('pb_manage_department_type', models.TextField(blank=True)),
                ('pb_manage_department_name', models.TextField(blank=True)),
                ('pb_qna_department_name', models.TextField(blank=True)),
                ('pb_qna_department_call', models.TextField(blank=True)),
                ('pb_qna_department_url', models.TextField(blank=True)),
                ('pb_category', models.TextField(blank=True)),
                ('pb_target_agerange', models.TextField(blank=True)),
                ('pb_target_area', models.TextField(blank=True)),
                ('pb_support_type', models.TextField(blank=True)),
                ('pb_disclosuer', models.TextField(blank=True)),
                ('pb_benefit_info', models.TextField(blank=True)),
                ('pb_sub_business', models.TextField(blank=True)),
                ('pb_statute', models.TextField(blank=True)),
                ('pb_manage_department_detail_part', models.TextField(blank=True)),
                ('pb_target_type', models.TextField(blank=True)),
                ('pb_support_cate', models.TextField(blank=True)),
                ('pb_update_date', models.DateTimeField(auto_now=True)),
                ('pb_dinga_agerange', models.TextField(blank=True, null=True)),
                ('pb_dinga_type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicUpdate',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('pb_name', models.TextField(blank=True)),
                ('pb_goal', models.TextField(blank=True)),
                ('pb_target', models.TextField(blank=True)),
                ('pb_criteria', models.TextField(blank=True)),
                ('pb_support_desc', models.TextField(blank=True)),
                ('pb_online_url', models.TextField(blank=True)),
                ('pb_submit_step', models.TextField(blank=True)),
                ('pb_submit_date', models.TextField(blank=True)),
                ('pb_need_paper', models.TextField(blank=True)),
                ('pb_manage_department_type', models.TextField(blank=True)),
                ('pb_manage_department_name', models.TextField(blank=True)),
                ('pb_qna_department_name', models.TextField(blank=True)),
                ('pb_qna_department_call', models.TextField(blank=True)),
                ('pb_qna_department_url', models.TextField(blank=True)),
                ('pb_category', models.TextField(blank=True)),
                ('pb_target_agerange', models.TextField(blank=True)),
                ('pb_target_area', models.TextField(blank=True)),
                ('pb_support_type', models.TextField(blank=True)),
                ('pb_disclosuer', models.TextField(blank=True)),
                ('pb_benefit_info', models.TextField(blank=True)),
                ('pb_sub_business', models.TextField(blank=True)),
                ('pb_statute', models.TextField(blank=True)),
                ('pb_manage_department_detail_part', models.TextField(blank=True)),
                ('pb_target_type', models.TextField(blank=True)),
                ('pb_support_cate', models.TextField(blank=True)),
            ],
        ),
    ]
