# Generated by Django 2.2.7 on 2020-01-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicdata',
            name='pb_update_date',
        ),
    ]
