# Generated by Django 2.2.7 on 2020-01-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_publicdata_pb_update_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicdata',
            name='pb_update_check',
            field=models.BooleanField(default='False'),
        ),
    ]
