# Generated by Django 2.2.7 on 2020-01-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_auto_20200105_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CascadeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40, verbose_name='닉네임')),
                ('belong_public', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_qna', to='public.PublicData')),
            ],
        ),
    ]
